---
openapi: 3.0.1
info:
  title: TODOS API
  version: v1
paths:
  "/auth/login":
    post:
      summary: Login
      tags:
      - Authentication
      description: Login to generate a token
      parameters: []
      responses:
        '200':
          description: successfull
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/signup":
    post:
      summary: Signup
      tags:
      - Authentication
      description: Signup to generate a token
      parameters: []
      responses:
        '201':
          description: created successfully
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
  "/todos/{todo_id}/items":
    parameters:
    - name: todo_id
      in: path
      description: todo_id
      required: true
      schema:
        type: string
    get:
      summary: Get all todo items
      tags:
      - Todo Items
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '422':
          description: invalid request
    post:
      summary: Create a new todo item
      tags:
      - Todo Items
      parameters: []
      security:
      - Bearer: []
      responses:
        '201':
          description: created
        '404':
          description: not found
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                done:
                  type: boolean
                  default: false
              required:
              - name
              - done
  "/todos/{todo_id}/items/{id}":
    parameters:
    - name: todo_id
      in: path
      description: todo_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Get a todo item
      tags:
      - Todo Items
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '422':
          description: invalid request
    put:
      summary: Update a todo item
      tags:
      - Todo Items
      parameters: []
      security:
      - Bearer: []
      responses:
        '204':
          description: successful with no content
        '404':
          description: not found
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                done:
                  type: boolean
              required:
              - name
              - done
    delete:
      summary: Delete a todo item
      tags:
      - Todo Items
      security:
      - Bearer: []
      responses:
        '204':
          description: successful with no content
        '404':
          description: not found
        '422':
          description: invalid request
  "/todos":
    get:
      summary: List all todos and todo items
      tags:
      - Todos
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
        '422':
          description: invalid token
    post:
      summary: Create a new todo
      tags:
      - Todos
      parameters: []
      security:
      - Bearer: []
      responses:
        '201':
          description: created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
              - title
  "/todos/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Get a todo
      tags:
      - Todos
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '422':
          description: invalid request
    put:
      summary: Update a todo
      tags:
      - Todos
      parameters: []
      security:
      - Bearer: []
      responses:
        '204':
          description: successful with no content
        '404':
          description: not found
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
              - title
    delete:
      summary: Delete a todo and its items
      tags:
      - Todos
      security:
      - Bearer: []
      responses:
        '204':
          description: successful with no content
        '404':
          description: not found
        '422':
          description: invalid request
servers:
- url: http://{defaultHost}:3000
  variables:
    defaultHost:
      default: 127.0.0.1
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: Your Bearer token
